---
name: Main branch continuous integration and snapshots deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.build/**'
      - '.github/workflows/deployment.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [
          { 'version': '8', 'source': 'releases', opts: '' },
          { 'version': '11', 'source': 'releases', opts: '' },
          { 'version': '16', 'source': 'nightly', 'opts': '--illegal-access=permit'  }  # required for kotlin on java 16
        ]
    name: Build with Java ${{ matrix.java.version }} (OpenJDK)
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-${{ matrix.java.version }}
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: ${{ matrix.java.version }}
          source: ${{ matrix.java.source }}
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -s .build/maven-ci-settings.xml -B clean verify

  snapshot:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-11
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
      - name: Deploy snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
        run: |
          .build/decrypt-secrets.sh
          .build/deploy-snapshot.sh

  quality:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-11
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
      - name: Coverage and Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
        run: |
          mvn -s .build/maven-ci-settings.xml verify -Pcoverage
          mvn -s .build/maven-ci-settings.xml sonar:sonar \
            -Dsonar.projectKey=smallrye_smallrye-mutiny \
            -Dsonar.projectName="SmallRye Mutiny" \
            -Dsonar.organization=smallrye \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_LOGIN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13

  compatibility:
    runs-on: ubuntu-20.04
    name: Compatibility Check
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-11
      - uses: actions/checkout@v2
      - name: Install JDK 11 (OpenJDK)
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          source: releases
      - name: Compatibility Check
        run: mvn -s .build/maven-ci-settings.xml -pl '!bom' -B install revapi:check@check-compatibility -DskipTests -fae
